### ISSUE TITLE
Closing the world makes the pestle disappear until you re-open the mortar

### ISSUE THREAD

**Issue by Nanoattack** [Nanoattack/Devilry#8]
How mortar looks after closing world
![image](https://github.com/Nanoattack/Devilry/assets/67018698/26b16667-b4ad-46e1-9b79-0fc2f52d2352)

After opening GUI
![image](https://github.com/Nanoattack/Devilry/assets/67018698/73b3ea4f-e53e-4e4c-be4f-4dfa4b8a5d95)

**Comment by Lvgraef** [comment]
Fixed
