### ISSUE TITLE
Grinding recipe only outputs 1 of any item

### ISSUE THREAD

**Issue by Nanoattack** [Nanoattack/Devilry#9]
![image](https://github.com/Nanoattack/Devilry/assets/67018698/14d4085f-413e-459a-b0f7-63e20b6786fe)
Should be 3 specified by recipe
![image](https://github.com/Nanoattack/Devilry/assets/67018698/cd32c1b0-8e75-49d6-a6f3-ff222ebaa9af)

Happens to every recipe

**Comment by Lvgraef** [comment]
Fixed
